### PR TITLE
Cloud setup

### PR DESCRIPTION
**Pull request by JerryRobertson**

### CODE REVIEW

**Comment by CharlesHunter** [comment]
Does this allow for CI/CD automation on merge to dev so we can test changes?

**Comment by JerryRobertson** [comment]
> Does this allow for CI/CD automation on merge to dev so we can test changes?

We do not have a dev branch, only the main and our personal branches. so I believe the correct answer is no?

**Comment by CharlesHunter** [comment]
> We do not have a dev branch, only the main and our personal branches. so I believe the correct answer is no?

Other projects *will* have a dev branch.  Will this work with githubs "automation" interface or is there a way to configure branch-specific deployment targets?

**Comment by CharlesHunter** [comment]
Approved for testing

**Review by CharlesHunter — APPROVED** [review]

**Pull request merged**
